DROP TABLE IF EXISTS users
CASCADE;

CREATE TABLE users
(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  date_of_birth DATE NOT NULL ,
  gender VARCHAR(255) NOT NULL,
  about TEXT,
  phone_number INTEGER NOT NULL,
  image VARCHAR(255) NOT NULL,
);