DROP TABLE IF EXISTS reviews
CASCADE;

CREATE TABLE reviews
(
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  therapist_id INTEGER REFERENCES therapists(id) ON DELETE CASCADE NOT NULL,
  review TEXT
);